userConfig:
        topic:   checkin_yelp

        key_by:   business_id

        date_field:   date
        date_format: '%Y-%m-%d %H:%M:%S'

        window:   1000.0

        schema:
            date:          String
            business_id:   String

        output_topic:   checkin_moving_count
        output_field:   count
        output_schema:
            business_id:   String
            count:         Integer
            date:          String
tenant: public
namespace: default
name: hash-test
inputs: [checkin_yelp]
output:  func_out
className: window_count.WindowCount
py:  /home/ec2-user/project/pfuncs/window_count.py
