userConfig:
        topic:    business_yelp 

        key_field:   [business_id, name]

        redis_server:  host.docker.internal 
        redis_port:    6379
        redis_id:      3

        group_catalog: 'catalog:categories'
        group_by:      categories

        schema:
            business_id: String
            # General info
            name:   String
            categories: [Array, String]
            is_open:   Integer
            hours:  [Map, String]
            stars:  Float
            review_count:  Integer
            attributes: [Map, String]
            # Location data
            state:   String
            city:    String
            postal_code: String
            address:  String
            longitude:  Float
            latitude:   Float
tenant: public
namespace: default
name:   store-business-geoindex 
inputs: [business_yelp]
output: business_geospatial_info 
className: geoindex.StoreGeoIndex 
py:  /project/pfuncs/geoindex.py
