broker:  pulsar://10.0.0.16:6650
topic:   checkin_window_count-INDEX 
name:    initialize-wc
max_records:   0 
schema:
    business_id:  String
    count:        Integer 
    date:  String
    timestamp:   Double 

initial_position:  earliest
timeout:     10
