broker:  pulsar://10.0.0.16:6650
topic:   checkin_crowd_ratio-INDEX
name:    initialize-wratio
max_records:   0
schema:
    business_id:        String
    crowd_ratio:         Float 
    date:               String
    max_count:          Integer

initial_position:  earliest
timeout:      1000
