userConfig:
        key_by:            business_id

        date_field:        date
        date_format:       '%Y-%m-%d %H:%M:%S'

        window:             8.64e4

        schema:
            date:          String
            business_id:   String
            timestamp:     Double

        output_field:      count
        output_schema:
            business_id:   String
            count:         Integer
            date:          String
            timestamp:     Double
tenant: public
namespace: default
name: window-count-INDEX
inputs: [checkin_yelp-INDEX]
output:  checkin_window_count-INDEX
className: window_count.WindowCount
py:  /home/ec2-user/project/pfuncs/window_count.py
