userConfig:
        key_by:   business_id
        value_field:  count

        state_server:  10.0.0.24
        state_port:    6379
        state_id:      1

        date_field:  date
        date_format: '%Y-%m-%d %H:%M:%S'

        window:   7.776e+6

        timestamp:         timestamp
        metric_period:     2000
        metric_topic:      'metric:window_max'

        schema:
            date:          String
            business_id:   String
            count:         Integer
            timestamp:     Float

        output_field:      max_count
        output_schema:
            business_id:   String
            max_count:     Integer
            date:          String

tenant: public
namespace: default
name: window-max
inputs: [checkin_window_count]
output:  checkin_window_max
className: window_max.WindowMax
py:  /home/ec2-user/project/pfuncs/window_max.py
